spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1522:XE
    username: devuser
    password: 1234

  thymeleaf:
    cache: false

  redis:
    client-type: lettuce
    lettuce:
      pool:
        max-active: 10 # 최대 커넥션 수 (음수면 무제한)
        max-idle: 10 # 커넥션 해제 없이 최대 연결 수
        min-idle: 5 # 커넥션 추가 생성 없이 최소 연결 수 
    port: 6379
    host: localhost

mybatis:
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml

server:
  port: 80
  
  